INSERT INTO CUST (CID, CUSTNAME, CUSTSURNAME, ADDRESS, PHONE) 
VALUES ('1', 'Ayla', 'Yilmaz', 'Bilkent/Ankara', '3122661245');

INSERT INTO CUST (CID, CUSTNAME, CUSTSURNAME, ADDRESS, PHONE) 
VALUES ('2', 'Zeki', 'Sozer', 'Bahceli/Ankara', '3122857415');

INSERT INTO CUST (CID, CUSTNAME, CUSTSURNAME, ADDRESS, PHONE) 
VALUES ('3', 'Jale', 'Sever', 'Bilkent/Ankara', '3122668574');

INSERT INTO CUST (CID, CUSTNAME, CUSTSURNAME, ADDRESS, PHONE) 
VALUES ('4', 'Emre', 'Turesin', 'Kizilay/Ankara', '3124212514');