DROP SEQUENCE RECNO;
DROP VIEW RECEIPT_DETAILS_VIEW;

ALTER TABLE RECEIPT_DETAILS DROP CONSTRAINT RECEIPT_DETAILS_FK1;
ALTER TABLE RECEIPT_DETAILS DROP CONSTRAINT RECEIPT_DETAILS_FK2;
ALTER TABLE RECEIPT DROP CONSTRAINT RECEIPT_FK1;

ALTER TABLE CUST DROP CONSTRAINT CUST_PK;
ALTER TABLE PRODUCT DROP CONSTRAINT PRODUCT_PK;
ALTER TABLE PRODUCT DROP CONSTRAINT PRODUCT_CHK;
ALTER TABLE RECEIPT DROP CONSTRAINT RECEIPT_PK;
ALTER TABLE RECEIPT_DETAILS DROP CONSTRAINT RECEIPT_DETAILS_PK;

DROP TABLE CUST CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE RECEIPT CASCADE CONSTRAINTS;
DROP TABLE RECEIPT_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CUST
(
CID NUMBER(4),
CUSTNAME VARCHAR2(15) NOT NULL,
CUSTSURNAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(20),
PHONE VARCHAR2(12),
CONSTRAINT CUST_PK PRIMARY KEY(CID)
);

CREATE TABLE PRODUCT
(
PID NUMBER(4),
PNAME VARCHAR2(20),
PRICE NUMBER(6,2),
CONSTRAINT PRODUCT_PK PRIMARY KEY(PID),
CONSTRAINT PRODUCT_CHK CHECK (PRICE > 0)
);

CREATE TABLE RECEIPT
(
RID NUMBER(4),
RDATE DATE DEFAULT SYSDATE,
CID NUMBER(4),
TOTAL NUMBER(6,2),
PAYMENT_TYPE VARCHAR2(10),
CONSTRAINT RECEIPT_PK PRIMARY KEY (RID),
CONSTRAINT RECEIPT_FK1 FOREIGN KEY (CID) REFERENCES CUST(CID)
);

CREATE TABLE RECEIPT_DETAILS(
RID NUMBER(4),
PID NUMBER(4),
QUANTITY NUMBER(3),
CONSTRAINT RECEIPT_DETAILS_PK PRIMARY KEY (RID, PID),
CONSTRAINT RECEIPT_DETAILS_FK1 FOREIGN KEY(PID) REFERENCES PRODUCT(PID),
CONSTRAINT RECEIPT_DETAILS_FK2 FOREIGN KEY(RID) REFERENCES RECEIPT(RID)
);

