INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('111', 'Ariel Deterjan 5kg', '22.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('112', 'Ariel Deterjan 10 kg', '40.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('113', 'Omomatik Sivi 1 kg.', '18.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('114', 'Suzme Peynir 800 gr', '12.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('115', 'Gemlik Zeytin', '18.50');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('116', 'Gursut Telli Kasar', '21.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('117', 'Tiryaki cay 1kg.', '20.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('118', 'Filiz Cay 500gr. ', '12.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('119', 'Dogus Çay 1 kg.', '21.90');

INSERT INTO PRODUCT (PID, PNAME, PRICE) 
VALUES ('120', 'Biskuvi 1 kg.', '8.90');