INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('1', '111', '1');
INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('1', '115', '2');
INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('1', '118', '1');
INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('2', '113', '1');
INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('3', '114', '1');
INSERT INTO RECEIPT_DETAILS (RID, PID, QUANTITY) VALUES ('3', '116', '1');

commit;