INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (recno.nextval, TO_DATE('09-DEC-15', 'DD-MON-RR'), 1, 72.80, 'VISA');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (recno.nextval, TO_DATE('07-DEC-15', 'DD-MON-RR'), 1, 17.01, 'CASH');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (recno.nextval, TO_DATE('10-DEC-15', 'DD-MON-RR'), 2, 34.80, 'VISA');
